### ISSUE TITLE
Keep links to bibliography and links to DOI?

### ISSUE THREAD

**Issue by gabrielastro** [keflavich/tex_compact_bib#3]
Hello!

Thanks a lot for this very helpful file! I get
```
pdfTeX warning (dest): name{cite.Smith+2000} has been referenced but does not e
xist, replaced by a fixed one
```
and the clickable links in the document point to "page 0", as hovering reveals, instead of to the bibliography.

Also, in the compact bibliography, is there a way of keeping the DOI links (to the published paper or at least the arXiv version), as for instance with `yahapj`? I am using `bibtex` and `pdflatex`, by the way, and my bibfile entries are from NASA ADS.

A few more small things:
 - If easy, could you provide the option of removing "References" at the beginning (I commented it out by hand) and then not put a `\textbullet~` before the first element? I am doing the latter by hand with: `sed -i '0,/\\textbullet~/{s///}' main.bbl` (thanks to an elegant [`GNU-sed` answer](https://stackoverflow.com/a/9453461))
 -  One more way to compactify is by replacing "**Smith** et al. 2010, arXiv e-prints, arXiv:1001.1001" with "**Smith** et al. 2010, arXiv:1001.1001". This too I am doing by hand, actually with a combined `bash` alias:
```
alias Th="pdflatex main.tex && bibtex main.bbl && sed -i '0,/\\\textbullet~/{s///}; s/, arXiv e-prints//g' main.bbl && pdflatex main.tex && pdflatex main.tex"
```
Maybe this could be baked in too…

In any case, thanks a lot!

**Comment by gabrielastro** [comment]
A few more things:
 - Treat the period at the end of "et~al." not as a sentence full stop because it is not right and also adds more space. This one too, I am currently changing with `sed` e.g. `{et~al.} 2010` into `et al.\ 2010` but a change at the source would be better. Unfortunately, I do not not the `bibtex` language…
 - Do not put a period at the end of the record. For this, I am currently removing periods at the ends of the lines but a few entries are longer and the period there is from "Vol." or "ed.", so that is not perfect.
 - The single-author entries have an initial for the first name. This should be removed, no, to be consistent? Or at least an option would be nice.
 - One could argue that letting "et al." mean "et alium" ("and one other") in the case of two-author papers is a bit of a cheat… Could the two-author papers be kept as "A & B" (again just the last names)?

Could maybe @aschmiedeke (who worked on #2) help? Thanks!

**Comment by keflavich** [comment]
These are some reasonably suggestions.  You're right about "et alium" being silly, but I do plan to coauthor a paper with some:
![image](https://github.com/keflavich/tex_compact_bib/assets/143715/21e5a5ba-48eb-4c2a-9660-35ff54c538d7)


I don't know bibtex well enough to just quickly make these changes, but if I get around to re-learning it and hacking more, I can try for some of these.  Otherwise, PRs are welcome if you come up with any fixes.

**Comment by gabrielastro** [comment]
:smile: I am sure you will have blooming success! Oops, I should have checked my Latin… "alius" it would be.

Thanks for your prompt answer! Unfortunately, I know no bibtex so cannot really help. I see that @lmytime has a fork with what looks like some improvements, so maybe he would be able to help!

By the way, `\usepackage{microtype}` also helps a bit to save space, as I saw recommended on a forum.

**Comment by lmytime** [comment]
Hi @gabrielastro , I make some improvements for self-use. It can keep links to the bibliography but I do not keep DOI items. I  can help with these when I have spare time.

**Comment by gabrielastro** [comment]
Thank you very much! Indeed, I see now that the links to the bibliography work, which is a very nice improvement. (@keflavich, maybe you could pull this?) Please let me know whenever you have had time for the other points.

**Comment by keflavich** [comment]
@lmytime I'd be happy to merge in changes if you want to make a pull request.  If you prefer to keep your fork independent, though, that's fine - maybe we should at least add links to it in the README here?

**Comment by lmytime** [comment]
@keflavich I re-hacked the `.bst` file from the newest version AAS template and improved a lot. Almost all files have been replaced. So it could not be better if you add a link to my repository: https://github.com/lmytime/tex_compact_bib
But if you prefer, I can make a pull request.

@gabrielastro I have included many suggestions you listed above. Please check my repository. Also, you can check the `.bst` file. I made many detailed comments for each code I changed from the original AAS `.bst` file. You can search `MLi` and tune any if you want.

**Comment by keflavich** [comment]
@lmytime I linked you from the README:
https://github.com/keflavich/tex_compact_bib/blob/master/README.rst

**Comment by gabrielastro** [comment]
@lmytime Thanks a lot for your improvements and for the helpful comments in the .bst files! (Sorry for the delay but I was and am travelling.) It is really good. Two things:
- There is an extra dot after two-author entries (e.g., "Smith & Lemaître. 1917")
- I tried modifying the .bst files to have "… et al.\ YYYY" but it does not work (I get an extra dot) and I do not know bibtex… Would that be possible too?

**Comment by gabrielastro** [comment]
Two more items for @lmytime (I wanted to add it to your fork but apparently one cannot):
- I did not realise that I did not test arXiv entries but I still get "XX et al. 2024, arXiv e-prints, arXiv:NNNN".
- Is it possible to have the first author's name in bold as a compromise in legibility? But only if this is easy to do.
In any case, thanks again!

**Comment by gabrielastro** [comment]
One more thing (for @lmytime, @aschmiedeke, @keflavich, or anyone else who understands .bst files well enough): The  style of ApJ, on which `tex_compact_bib` is based, is to sort alphabetically by first author, then by co-author(s)'(s) name(s), and then by year. (A&A, for comparison, sorts by first author's name and then directly by year and not by the name(s) of further author(s).) This leads to papers in `tex_compact_bib` style that in general seem to be sorted randomly for a given author, which looks strange especially for several "et al." papers. I am not sure how difficult it would be to:
- sort only by first author and year,
- and only for several papers in one year then sort by second author, and only then have the "et al." papers (but [be careful](https://scholar.google.nl/citations?user=qGuYgMsAAAAJ) :wink:).
Thanks!

**Comment by gabrielastro** [comment]
To fix the extra dot, to simplify the "arXiv" entries, and to add `\ ` after "et al.", one can do for now:
```bash
sed -i 's/}\./}/g; s/, arXiv e-prints//g; s/{et~al\.} /et~al.\\ /g' main.bbl
```
This thus fixes most of the issues above (and no guarantees but it does seem robust to long names, line breaks, etc.). In case this can be of use to anyone…

To do this with Overleaf, you need to add the `.bbl` file to the project and in your document to include it and comment out the bibliography:
```latex
% \bibliography{papers.bib}
\input{main.bbl}
```
Of course, if you add or remove references, do not forget to un-/-uncomment those lines, re-run `sed`, and re-upload the `.bbl` file. (I get the `.bbl` file by downloading the project on my computer with `git` and compiling locally.) By the way, the `.bbl` file added by hand to Overleaf will not get overwritten, just shadowed, by Overleaf's version when compiling with an active `\bibliography{}` command.

**Comment by lmytime** [comment]
Thanks @gabrielastro , I will consider including your suggestion when I have time.

**Comment by keikun555** [comment]
@lmytime when using the numeric version I found that the years were becoming "????" even though they were present in the .bib file. Did a quick scan and I think https://github.com/lmytime/tex_compact_bib/blob/master/aas_compact-numeric.bst#L856 needs to say "year" instead of "year.addlink". Making this change seems to have worked for me.

Also @keflavich I believe there's an extra ")" in the link to @lmytime 's branch.

**Comment by gabrielastro** [comment]
To add to this, @lmytime, I finally dug a bit into the `.bst` style file and fixed the repetitive "arXiv e-prints, arXiv:…": after the `FUNCTION {first.page} …` block, put (replacing also the current `FUNCTION {format.journal}`:
```
FUNCTION {or}
{
{ pop$ #1 }
’skip$
if$
}

%%%%%%%%%%% Comment by MLi: The original codes will show arXiv paper as `arXiv, arXiv:xxxx.xxxxx`. We cancel the duplicate of arXiv.
%%%%% addition by GDM: add the case that the journal is "arXiv e-prints"
%%%%%  and introduce the "or" function (thanks to the bibtex manual!)
FUNCTION {format.journal}
{ journal empty$
  journal "arXiv" =
  or
  journal "arXiv e-prints" =
  or
    { "" }
    { journal }
  if$
}
%%%%%%%%%%%
```
I had not realised but from arXiv, sometimes the journal is "arXiv", sometimes "arXiv e-prints", and that was the problem. The `or` function makes it more elegant. Thanks to the manual! Reverse Polish notation is really not so bad after all :).

**Comment by lmytime** [comment]
> @lmytime when using the numeric version I found that the years were becoming "????" even though they were present in the .bib file. Did a quick scan and I think https://github.com/lmytime/tex_compact_bib/blob/master/aas_compact-numeric.bst#L856 needs to say "year" instead of "year.addlink". Making this change seems to have worked for me.
> 
> Also @keflavich I believe there's an extra ")" in the link to @lmytime 's branch.

Could you show the bib file with ???? item? Or could you please create an issue in my branch and submit a pull request?

**Comment by lmytime** [comment]
> To add to this, @lmytime, I finally dug a bit into the `.bst` style file and fixed the repetitive "arXiv e-prints, arXiv:…": after the `FUNCTION {first.page} …` block, put (replacing also the current `FUNCTION {format.journal}`:
> 
> ```
> FUNCTION {or}
> {
> { pop$ #1 }
> ’skip$
> if$
> }
> 
> %%%%%%%%%%% Comment by MLi: The original codes will show arXiv paper as `arXiv, arXiv:xxxx.xxxxx`. We cancel the duplicate of arXiv.
> %%%%% addition by GDM: add the case that the journal is "arXiv e-prints"
> %%%%%  and introduce the "or" function (thanks to the bibtex manual!)
> FUNCTION {format.journal}
> { journal empty$
>   journal "arXiv" =
>   or
>   journal "arXiv e-prints" =
>   or
>     { "" }
>     { journal }
>   if$
> }
> %%%%%%%%%%%
> ```
> 
> I had not realised but from arXiv, sometimes the journal is "arXiv", sometimes "arXiv e-prints", and that was the problem. The `or` function makes it more elegant. Thanks to the manual! Reverse Polish notation is really not so bad after all :).

Thank you, @gabrielastro . It is indeed a case. Could you please make a pull request in my branch?

**Comment by gabrielastro** [comment]
Thanks, @lmytime! If your kind concern is about somehow giving me the credit, please just go ahead and make the change directly in your branch :smile:! No problem. You can replace "GDM" by "MLi" for simplicity. Otherwise, let me know, and I can try it.

**Comment by gabrielastro** [comment]
The only two remaining problems are: 1.) the extra period after single- and two-author entries, 2.) having "et al.\ " instead of "et al. " (which is correct and also saves space since the space is thinner :nerd_face:).

**Comment by gabrielastro** [comment]
Discovered serendipitously just now: to make a (listed) author name bold, one could slightly adapt the function provided at https://tex.stackexchange.com/questions/361666/why-is-the-bst-hack-for-highlighting-author-name-not-working! Maybe you can add an easy-to-comment-in-out block in case someone needs this.

**Comment by keikun555** [comment]
> > @lmytime when using the numeric version I found that the years were becoming "????" even though they were present in the .bib file. Did a quick scan and I think https://github.com/lmytime/tex_compact_bib/blob/master/aas_compact-numeric.bst#L856 needs to say "year" instead of "year.addlink". Making this change seems to have worked for me.
> > Also @keflavich I believe there's an extra ")" in the link to @lmytime 's branch.
> 
> Could you show the bib file with ???? item? Or could you please create an issue in my branch and submit a pull request?

Thanks for the quick reply! Here's an example entry where the year becomes ???? in the generated .bbl file
```
@Book{robinson,
  author       = "Abraham Robinson",
  title        = "Non-standard Analysis",
  year         = "1996",
}
```
Here's the entry in the generated .bbl file
```
\bibitem[{Robinson(1996)}]{robinson}
Robinson. ????, Non-standard Analysis;
```
In the warnings section of the .blg logs we get
```
Warning--empty year in robinson; set to ????
```
It seems the issues tab in the branch isn't enabled, so I can just make the PR -- hope that's okay.

**Comment by gabrielastro** [comment]
Does the error go away if you write `{1996}` for the year insteaf of in quotes?

**Comment by keikun555** [comment]
I've tried the following
* 1996
* "1996"
* {1996}

All of them seem to not work. Also, I do prefer to use "1996" because I use bibclean to keep my bib files pretty, and I'm not sure how to change the default year format in that tool.

**Comment by lmytime** [comment]
Dear @keikun555, I carefully debug your case. It is due to the lines 832-843:
```tex
FUNCTION {format.year.addlink}
{ doi empty$
{eprint empty$ 
     { url empty$ 
       { "" }
       { format.year.addlink.url }
     if$}
     { format.year.addlink.eprint }
    if$}
  { format.year.addlink.doi }
  if$
}
``` 
The logic is to add a URL link to the `year` element, and the final formated year is called `format.year.addlink`.
It has a bug here, should replace it with:
```tex
FUNCTION {format.year.addlink}
{ doi empty$
{eprint empty$ 
     { url empty$ 
       { year }
       { format.year.addlink.url }
     if$}
     { format.year.addlink.eprint }
    if$}
  { format.year.addlink.doi }
  if$
}
``` 
It means just using the `year` itself if there is no link keyword. Please check whether it works. 
If it works, please update the pull request branch. Thanks!

**Comment by lmytime** [comment]
> To add to this, @lmytime, I finally dug a bit into the `.bst` style file and fixed the repetitive "arXiv e-prints, arXiv:…": after the `FUNCTION {first.page} …` block, put (replacing also the current `FUNCTION {format.journal}`:
> 
> ```
> FUNCTION {or}
> {
> { pop$ #1 }
> ’skip$
> if$
> }
> 
> %%%%%%%%%%% Comment by MLi: The original codes will show arXiv paper as `arXiv, arXiv:xxxx.xxxxx`. We cancel the duplicate of arXiv.
> %%%%% addition by GDM: add the case that the journal is "arXiv e-prints"
> %%%%%  and introduce the "or" function (thanks to the bibtex manual!)
> FUNCTION {format.journal}
> { journal empty$
>   journal "arXiv" =
>   or
>   journal "arXiv e-prints" =
>   or
>     { "" }
>     { journal }
>   if$
> }
> %%%%%%%%%%%
> ```
> 
> I had not realised but from arXiv, sometimes the journal is "arXiv", sometimes "arXiv e-prints", and that was the problem. The `or` function makes it more elegant. Thanks to the manual! Reverse Polish notation is really not so bad after all :).

Hi @gabrielastro , I think the `or` function is already in the `.bst` file, isn't it?  It is in line 300, I think. So I should only update the lower code block, right?

**Comment by gabrielastro** [comment]
Oh! Sorry, I had not realised. Yes, of course!

**Comment by lmytime** [comment]
> Oh! Sorry, I had not realised. Yes, of course!

Thank you @gabrielastro . Also, could you please let me know: how do you generate the `.bib` file with `journal=arXiv e-prints`?

**Comment by gabrielastro** [comment]
Practically all my entries are from NASA ADS, and only a few contain this, all from the last two years… Not sure. It might be entries that I copied as soon as they  appeared on ADS… Thanks in any case for including this!

**Comment by lmytime** [comment]
> Practically all my entries are from NASA ADS, and only a few contain this, all from the last two years… Not sure. It might be entries that I copied as soon as they appeared on ADS… Thanks in any case for including this!

pushed to my branch.

**Comment by gabrielastro** [comment]
Thanks! I would also have removed the semicolons between the entries but that is a small one and easy to change again.

**Comment by lmytime** [comment]
> Discovered serendipitously just now: to make a (listed) author name bold, one could slightly adapt the function provided at https://tex.stackexchange.com/questions/361666/why-is-the-bst-hack-for-highlighting-author-name-not-working! Maybe you can add an easy-to-comment-in-out block in case someone needs this.

Thanks for this. It is easy to bold this. By changing the line 483 from
`"{vv~}{ll}" format.name$` to `"{vv~}\textbf{ll}" format.name$`.

**Comment by lmytime** [comment]
> Thanks! I would also have removed the semicolons between the entries but that is a small one and easy to change again.

Yes. That sounds good in some cases. Maybe I should consider allowing some user configuration, in the future...

**Comment by gabrielastro** [comment]
> > Discovered serendipitously just now: to make a (listed) author name bold, one could slightly adapt the function provided at https://tex.stackexchange.com/questions/361666/why-is-the-bst-hack-for-highlighting-author-name-not-working! Maybe you can add an easy-to-comment-in-out block in case someone needs this.
> 
> Thanks for this. It is easy to bold this. By changing the line 483 from `"{vv~}{ll}" format.name$` to `"{vv~}\textbf{ll}" format.name$`.

Thanks but this is for all authors whereas one might be interested (for an application) in highlighting only one's own name; that is what the function on stackexchange is doing.

**Comment by lmytime** [comment]
Ah~ Got it. That makes sense. Marked it.

**Comment by keikun555** [comment]
Thanks @lmytime I updated the PR with https://github.com/keflavich/tex_compact_bib/issues/3#issuecomment-2364045781

**Comment by gabrielastro** [comment]
Hello @lmytime or @keikun555 or someone else! One "major" issue still seems to be left: the extra period after single- or two-author papers:
```latex
{Betti} {et~al.} \dodoifor{…     % is ok
…
{Canup} \& {Ward}. \dodoifor{…   % there should not be a dot here
…
{Ward}. \dodoifor{…              % here neither!
```
I looked in detail at the source code and cannot find where the period is getting added! In fact, if I change all the `{et~al.}` to `{et~al\@}`, where `\@` in LaTeX apparently adds a period with no extra space afterwards (which would be nice out of principle and to gain space, but that is minor), the `.bbl` file contains:
```latex
{Betti} {et~al\@}. \dodoifor{ …  % now there is a dot outside
```
Thus some mechanism seems to detect that there is no dot in the `{…}` and adds one afterwards. Surprisingly (to me), the output PDF does not show two dots (one from `\@` and one from the explicit `.`), so really, I do not understand the `\@` but that is a separate issue…

But in any case, thank you again so much for this so-practical package!

**Comment by lmytime** [comment]
Hi @gabrielastro , I have resolved this issue.

Please check this position:
```bst
FUNCTION {output.nonnull}
{ 's :=
  output.state mid.sentence =
    { ", " * write$ }
    { output.state after.block =
        { add.period$ write$
          newline$
          "\newblock " write$
        }
        { output.state before.all =
            'write$
            %%% MLi: remove the period after the author list
            % { add.period$ " " * write$ }
            { add.blank$ " " * write$ }
          if$
        }
      if$
      mid.sentence 'output.state :=
    }
  if$
  s
}
```

Just replace the `add.period` here to `add.blank`, in the `output.state before.all`.

**Comment by gabrielastro** [comment]
Hello @lmytime, thank you so much! (I should have thought of searching for "period" in the `bibtex` manual.) Since it is the more common style (at least in the big astronomy journals), maybe that should be the default, with a little note in the README or so? In any case, thanks again!

Small ones: jouornal → journal; truanate → truncate

_Note: ` ```bst ` gives syntax highlighting on github_ 🤓… _You can edit your answer_ :wink:.

**Comment by gabrielastro** [comment]
Sorry but how is `add.blank` defined? It does not seem to be an internal function and it gives me (with `BibTeX, Version 0.99d (TeX Live 2019/Debian)`) an error… Or more generally: apart from changing the one line above, what else do I need to do?

**Comment by lmytime** [comment]
```bst
FUNCTION {add.blank}
{  " " * before.all 'output.state :=
}
```

**Comment by gabrielastro** [comment]
Sorry but I am getting something strange: whether I put `FUNCTION {add.blank} …` right before or right after the `FUNCTION {output.nonnull}`, I get:
```
add.blank$ is an unknown function---line 232 of file aas_compact.bst
add.blank is already a type "wizard-defined" function name
---line 290 of file aas_compact.bst
```
because it was actually already defined in the file (sorry), further down (line 290±1 or so). If I comment out that original definition (line 290), I just get the `add.blank$ is an unknown function---line 232 of file aas_compact.bst` (where line 232 contains just `{ add.blank$ " " * write$ }`) error for a definition before or after `FUNCTION {output.nonnull}`.

**Comment by gabrielastro** [comment]
@lmytime No rush but since it seemed to work for you but not for me, do you know what the problem is? Should you maybe push your new version with this (no period) as a default setting and I will compare my file to it? Thanks!

**Comment by lmytime** [comment]
Hi @gabrielastro , sorry I am late. I did not update my code on github repository (I will do it sometime later). But I made a project webpage, you can check the latest codes and a minimal demo on Overleaf.
https://preview.lmytime.com/bibcompact/
